In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("homeprices.csv")

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
df['bedrooms']

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

# Missing Value add

In [17]:
new=df.bedrooms.median()

In [19]:
new

4.0

In [21]:
df.bedrooms = df.bedrooms.fillna(new)

In [23]:
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [25]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [27]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [29]:
df.head(3)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000

In [32]:
df.shape

(6, 4)

In [36]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

# Separate X and Y

In [40]:
x = df.drop(['price'], axis=1)

In [42]:
x

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [47]:
y = df.price

In [49]:
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

# Splitting dataset into Training set and Testing set

In [51]:
from sklearn.model_selection import train_test_split

In [53]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=.30, random_state=1)

In [55]:
xtrain

area  bedrooms  age
4  4000       5.0    8
0  2600       3.0   20
3  3600       3.0   30
5  4100       6.0    8

In [57]:
ytrain

4    760000
0    550000
3    595000
5    810000
Name: price, dtype: int64

In [59]:
from sklearn.linear_model import LinearRegression

In [63]:
reg = LinearRegression()

In [65]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [79]:
xtest

area  bedrooms  age
2  3200       4.0   18
1  3000       4.0   15

# Prediction

In [69]:
reg.predict(xtest)

array([638833.33333333, 632166.66666667])

In [71]:
reg.predict([(3300, 4.1, 17)])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([652316.66666667])

In [73]:
reg.coef_

array([   68.33333333, 43166.66666667, -2333.33333333])

In [75]:
reg.intercept_

289500.0

In [77]:
y = 68.33333333*3300 + 43166.66666667*4.1 + (-2333.33333333)*17 + 289500.0

In [78]:
y

652316.666655737